{{ if .Values.apps }}
{{- range $project := .Values.apps }}
{{- if $project.enabled }}
{{- range $component := $project.components }}
{{- if not (hasKey $component "wordpress") }}

{{- /* initialize `projectEnvironment` variable with either `$project.environment` if it exists or with `$.Values.environment` otherwise */}}
{{ $projectEnvironment := ternary $project.environment $.Values.environment (hasKey $project "environment") -}}

{{- $data := dict "project"           $project
                  "component"         $component
                  "environment"       $projectEnvironment
                  "namespace"         $.Release.Namespace
                  "storageClassName"  $.Values.storageClassName }}

# workspace pvc contains git repo cloned for the component by tekton
{{ include "tekton-apps.tekton-pvc" (set (set $data "suffix" "workspace-pvc")        "storage" "10Gi") }}
{{ if contains "buildpack" $component.pipeline }}
# buildpacks cache pvc contains cache layers used by buildpacks
{{ include "tekton-apps.tekton-pvc" (set (set $data "suffix" "buildpacks-cache-pvc") "storage" "5Gi") }}
{{- end }}

{{- end }} {{- /* if not component.wordpress */}}
{{- end }} {{- /* range component */}}
{{- end }} {{- /* if project.enabled */}}
{{- end }} {{- /* range */}}
{{- end }} {{- /* if apps */}}
