{{ if .Values.apps }}
{{- range $project := .Values.apps }}
{{- if $project.enabled }}
{{- range $component := $project.components }}
{{- if hasKey $component "wordpress" }}

# initialize `projectEnvironment` variable with either `$project.environment` if it exists or with `$.Values.environment` otherwise
{{ $projectEnvironment := ternary $project.environment $.Values.environment (hasKey $project "environment") -}}

{{- $data := dict "project"           $project
                  "component"         $component
                  "environment"       $projectEnvironment }}

# initialize `argocd` variable with either `$component.argocd` dict if it exists or with empty dict
{{ $argocd := ternary $component.argocd dict (hasKey $component "argocd") -}}

# ========================================================================
# ðŸŒ± {{ $project.project | upper }}/{{ $component.name | upper }} COMPONENT TRIGGER BINDING
# ========================================================================
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name:  {{ include "tekton-apps.resourceName" $data }}-env
  namespace: {{ $.Release.Namespace }}
spec:
  params:
  - name: application
    value: {{ coalesce $argocd.appName (include "tekton-apps.resourceName" $data) }}
  - name: project
    value: {{ $project.project }}
  - name: component
    value: {{ $component.name }}
  - name: namespace
    value: {{ include "tekton-apps.set-namespace-from-component-or-project" (dict "component" $component "project" $project "component_name" "component") }}
  {{- include "tekton-apps.get-triggerbinding-value-or-default" (dict "triggerBinding" $component.triggerBinding "name" "environment" "default" $projectEnvironment ) | nindent 2 }}
  - name: gitRevision
    value: $(extensions.branch_name)
  - name: sha
    value: $(extensions.truncated_sha)
  {{- include "tekton-apps.get-triggerbinding-value-or-default" (dict "triggerBinding" $component.triggerBinding "name" "kubernetes_namespace" "default" ( include "tekton-apps.set-namespace-from-component-or-project" (dict "component" $component "project" $project) ) ) | nindent 2 }}
  {{- if hasKey $project "kubernetesRepository" }}
  - name: kubernetes_repository_ssh_url
    value: {{ $project.kubernetesRepository.url }}
  - name: kubernetes_branch
    value: {{ $project.kubernetesRepository.branch }}
  {{- end }}
  - name: kustomization_path
    value: apps/wordpress/{{ $projectEnvironment }}/kustomization.yaml
