apiVersion: v2
name: capacity-prometheus-exporter

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1-dev-4

maintainers:
  - url: https://www.saritasa.com/
    name: Saritasa
    email: nospam@saritasa.com

description: |
  A Kubernetes's helm chart for a exporter that get information about Kubernetes nodes and serve the results in order to be scrapped by Prometheus
