apiVersion: v2
name: opsgenie-heartbeat

type: application


# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.3

maintainers:
  - url: https://www.saritasa.com/
    name: Saritasa
    email: nospam@saritasa.com

description: |
  Chart that installs our solution to send heartbeat pings via OpsGenie API automatically

  You will need to create the secret containing opsgenie APIKEY first:

  ```sh
  kubectl -n opsgenie create secret generic opsgenie-apikey-secret \
    --from-literal=apikey=YOUR_APIKEY
  ```

  Keep in mind that the name of your heartbeat in opsgenie should be the exact name of your kubernetes cluster
